{% set name = "pulsar-client" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b2dc186cd3ac2d80f24f12b2f4d731f4b464248e8ce34ff0579526df2403784e

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed     # [not win]
    - m2-sed  # [win]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libpulsar
    - pybind11
  run:
    - python
    - certifi

test:
  imports:
    - pulsar
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/apache/pulsar-client-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar Python client library

extra:
  recipe-maintainers:
    - xhochy
