{% set name = "pulsar-client" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bc26ef00c0bc1201c465fcb1753e024b77bba4eaf279738b587089b356c0bc7a

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed     # [not win]
    - m2-sed  # [win]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - libpulsar
    - pybind11
  run:
    - python
    - certifi

test:
  imports:
    - pulsar
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/apache/pulsar-client-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar Python client library

extra:
  recipe-maintainers:
    - xhochy
