{% set name = "pulsar-client" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5bfd0e8974de89cb5ab319100c7d4c8a83c8a6951b634987483c173b4a0b047a

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - libpulsar
    - pybind11
  run:
    - python
    - certifi

test:
  imports:
    - pulsar
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/apache/pulsar-client-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar Python client library

extra:
  recipe-maintainers:
    - xhochy
