{% set name = "pulsar-client" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 72126355be58eb53701f7a0e4652ea0a04386df449b6b34686f001bcbde04f65

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed     # [not win]
    - m2-sed  # [win]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - libpulsar
    - pybind11
  run:
    - python
    - certifi

test:
  imports:
    - pulsar
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/apache/pulsar-client-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar Python client library

extra:
  recipe-maintainers:
    - xhochy
